export const GET_ALL_COMMENT = "GET_ALL_COMMENT";
export const GET_ALL_COMMENT_SAGA = "GET_ALL_COMMENT_SAGA";

export const DELETE_COMMENT_SAGA = "DELETE_COMMENT_SAGA";

export const ADD_COMMENT_SAGA = "ADD_COMMENT_SAGA";