export const GET_USER_BY_PROJECT_ID_SAGA = "GET_USER_BY_PROJECT_ID_SAGA";
export const GET_USER_BY_PROJECT_ID = "GET_USER_BY_PROJECT_ID";

export const USER_SIGN_UP_SAGA = "USER_SIGN_UP_SAGA";

export const GET_ALL_USER = "GET_ALL_USER";
export const GET_ALL_USER_SAGA = "GET_ALL_USER_SAGA";